### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by Gurenduben** [fredsta98/keys-generator-binaries#1]
How do i run the exe files? I tried clicking, opening as administrator, i even tried cmd but I can’t open them

**Comment by fredsta98** [comment]
I assumed people would get the instructions from the original source. My bad. Simple run it like this:

`key-generator.exe btc {page}` however a more efficient way to run this is actually to move the binary to a folder in program files, then adding the .exe file to path. That way you can open a terminal in any directory and run `key-generator btc {page}` Page being an integer between 1 and 904625697166532776746648320380374280100293470930272690489102837043110636675. However this is different for the versions that print more keys per page. 

I'll be sure to edit the ReadMe file and provide instructions on how to run this.

**Comment by Gurenduben** [comment]
It worked thank you very much
